// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ColumnList: typeof import('./src/components/ColumnList.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    DropdownItem: typeof import('./src/components/DropdownItem.vue')['default']
    GlobalHeader: typeof import('./src/components/GlobalHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
